name: test_task
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  gradient_borders: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: montserratAlternates
      fonts:
        - asset: assets/fonts/Montserrat_Alternates/MontserratAlternates-Regular.ttf
        - asset: assets/fonts/Montserrat_Alternates/MontserratAlternates-Italic.ttf
          style: italic
        - asset: assets/fonts/Montserrat_Alternates/MontserratAlternates-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat_Alternates/MontserratAlternates-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Montserrat_Alternates/MontserratAlternates-Thin.ttf
          weight: 100
        - asset: assets/fonts/Montserrat_Alternates/MontserratAlternates-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Montserrat_Alternates/MontserratAlternates-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat_Alternates/MontserratAlternates-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Montserrat_Alternates/MontserratAlternates-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat_Alternates/MontserratAlternates-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Montserrat_Alternates/MontserratAlternates-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat_Alternates/MontserratAlternates-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Montserrat_Alternates/MontserratAlternates-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat_Alternates/MontserratAlternates-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Montserrat_Alternates/MontserratAlternates-Black.ttf
          weight: 900
        - asset: assets/fonts/Montserrat_Alternates/MontserratAlternates-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Montserrat_Alternates/MontserratAlternates-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat_Alternates/MontserratAlternates-ExtraLightItalic.ttf
          weight: 200
          style: italic
